
import React, { createContext, useContext, useState, ReactNode } from 'react';
import { Language } from '../types';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  pt: {
    // Theme
    'theme.light': 'Claro',
    'theme.dark': 'Escuro',
    'theme.auto': 'Auto',

    // Nav
    'nav.home': 'Início',
    'nav.tools': 'Ferramentas',
    'nav.projects': 'Projetos',
    'nav.ai': 'IA Expert',
    
    // Dashboard
    'dash.welcome': 'Bem-vindo(a),',
    'dash.engineer': 'Engenheiro',
    'dash.calc_voltage': 'Calc. Tensão',
    'dash.ask_ai': 'Consultar IA',
    'dash.daily_summary': 'Resumo do Dia',
    'dash.today': 'Hoje',
    'dash.calcs_performed': 'Cálculos Realizados',
    'dash.pending_projects': 'Projetos Pendentes',
    'dash.add_note': 'Adicionar Nota de Campo',
    'dash.tip_title': 'DICA DO DIA',
    'dash.tip_text': '"Sempre verifique a ausência de tensão com um testador calibrado antes de tocar. Teste-Antes-de-Tocar."',
    'dash.backup_title': 'Segurança de Dados',
    'dash.backup_export': 'Fazer Backup (Exportar)',
    'dash.backup_import': 'Restaurar Dados (Importar)',
    'dash.backup_success': 'Dados restaurados com sucesso!',
    'dash.backup_error': 'Erro ao ler arquivo. Verifique o formato.',
    'dash.rate_title': 'Gostando do App?',
    'dash.rate_desc': 'Sua avaliação nos ajuda a criar mais ferramentas gratuitas.',
    'dash.rate_btn': 'Avaliar Agora ⭐',

    // Calculators
    'tools.title': 'Ferramentas de Engenharia',
    'tools.voltage_drop': 'Queda de Tensão',
    'tools.voltage_drop_desc': 'Calcular % de queda baseada em distância e carga.',
    'tools.ohms_law': 'Lei de Ohm',
    'tools.ohms_law_desc': 'Relações básicas V = I x R.',
    'tools.conduit': 'Ocupação de Eletrodutos',
    'tools.conduit_desc': 'Dimensionamento NBR/NEC.',
    'tools.power_factor': 'Fator de Potência',
    'tools.power_factor_desc': 'Correção de banco de capacitores.',
    'tools.breaker': 'Dim. Disjuntores',
    'tools.breaker_desc': 'Seleção de proteção baseada na carga.',
    'tools.safety': 'Checklist NR-10',
    'tools.safety_desc': 'Verificação de segurança pré-tarefa.',
    'tools.status_dev': 'Em Breve',
    'tools.status_avail': 'Disponível',

    // Voltage Drop Calc
    'vd.title': 'Calculadora de Queda de Tensão',
    'vd.voltage': 'Tensão do Sistema (V)',
    'vd.current': 'Corrente (Amperes)',
    'vd.distance': 'Distância (metros)',
    'vd.cable': 'Seção do Cabo (mm²)',
    'vd.material': 'Material',
    'vd.copper': 'Cobre (Cu)',
    'vd.aluminum': 'Alumínio (Al)',
    'vd.result_drop': 'Queda de Tensão',
    'vd.ok': 'OK',
    'vd.high': 'Queda Alta',
    'vd.warning': 'Aviso: Queda excede 4%. Considere aumentar o cabo para',

    // Ohms Law
    'ohm.title': 'Lei de Ohm & Potência',
    'ohm.subtitle': 'Preencha quaisquer 2 valores para calcular os restantes.',
    'ohm.v': 'Tensão (V)',
    'ohm.i': 'Corrente (A)',
    'ohm.r': 'Resistência (Ω)',
    'ohm.p': 'Potência (W)',
    'ohm.clear': 'Limpar',

    // Conduit Fill
    'cf.title': 'Taxa de Ocupação',
    'cf.conduit_size': 'Tamanho do Eletroduto (pol)',
    'cf.wire_size': 'Seção do Cabo (mm²)',
    'cf.num_wires': 'Número de Condutores',
    'cf.max_fill': 'Máximo Permitido (40%)',
    'cf.actual_fill': 'Ocupação Atual',
    'cf.status_ok': 'Aprovado',
    'cf.status_over': 'Sobrecarregado',
    'cf.add_wire': '+ Cabo',
    'cf.remove_wire': '- Cabo',

    // Power Factor
    'pf.title': 'Correção de Fator de Potência',
    'pf.active_power': 'Potência Ativa (kW)',
    'pf.current_pf': 'Fator de Potência Atual',
    'pf.target_pf': 'Fator de Potência Alvo',
    'pf.required_kvar': 'Banco de Capacitores Necessário',
    'pf.calc_btn': 'Calcular kVAR',

    // Breaker Sizing
    'cb.title': 'Dimensionamento de Disjuntor',
    'cb.mode': 'Modo de Cálculo',
    'cb.mode_p': 'Por Potência (W)',
    'cb.mode_i': 'Por Corrente (A)',
    'cb.power': 'Potência da Carga (Watts)',
    'cb.voltage': 'Tensão (V)',
    'cb.phases': 'Fases do Sistema',
    'cb.pf': 'Fator de Potência (cos φ)',
    'cb.calc_current': 'Corrente de Projeto (Ib)',
    'cb.rec_breaker': 'Disjuntor Recomendado (In)',
    'cb.min_cable': 'Cabo Mínimo Sugerido',
    'cb.note': 'Nota: O disjuntor (In) deve ser maior que a corrente de projeto (Ib) e menor que a capacidade do cabo (Iz).',

    // Safety Checklist
    'safe.title': 'Checklist de Segurança',
    'safe.cat_ppe': 'EPIs (Equip. de Proteção Individual)',
    'safe.cat_proc': 'Procedimentos e Isolamento',
    'safe.cat_tools': 'Ferramentas e Ambiente',
    'safe.item_head': 'Capacete com jugular (Classe B)',
    'safe.item_eyes': 'Óculos de proteção / Viseira',
    'safe.item_hands': 'Luvas isolantes (Classe correta para a tensão)',
    'safe.item_boots': 'Botas dielétricas',
    'safe.item_loto': 'Bloqueio e Etiquetagem (LOTO) aplicado',
    'safe.item_test': 'Ausência de Tensão verificada (Testar-Antes-Tocar)',
    'safe.item_tools': 'Ferramentas isoladas (1000V) em bom estado',
    'safe.item_dry': 'Área seca e sinalizada',
    'safe.btn_verify': 'Validar Segurança',
    'safe.alert_title': 'Itens Pendentes!',
    'safe.alert_desc': 'Você não pode prosseguir. Sua segurança está em risco. Por favor, verifique os seguintes itens:',
    'safe.success_title': 'Pronto para o Trabalho',
    'safe.success_desc': 'Todos os protocolos de segurança foram verificados. Trabale com cuidado.',
    'safe.reset': 'Novo Checklist',

    // AI Consultant
    'ai.title': 'Consultor Técnico IA',
    'ai.mode.general': 'Geral',
    'ai.mode.norm': 'Normas (NBR/NEC)',
    'ai.mode.safety': 'Segurança',
    'ai.welcome': 'Olá. Sou o VoltMaster AI. Posso ajudar com normas NBR/NEC, cálculos o checklists de segurança.',
    'ai.analyzing': 'Analisando parâmetros...',
    'ai.placeholder.general': 'Descreva seu problema elétrico...',
    'ai.placeholder.norm': 'Pergunte sobre tipos de cabos, eletrodutos...',
    'ai.placeholder.safety': 'Pergunte sobre procedimentos LOTO, EPIs...',
    'ai.error': 'Erro de conexão. Verifique sua internet.',
    'ai.disclaimer': 'Aviso: A IA pode cometer erros. Sempre verifique as informações com normas técnicas oficiais e consulte um profissional.',

    // Projects
    'proj.title': 'Projetos',
    'proj.details': 'Detalhes do Projeto',
    'proj.new_btn': 'Novo Projeto',
    'proj.edit_title': 'Editar Projeto',
    'proj.new_title': 'Novo Projeto',
    'proj.search': 'Buscar por nome ou cliente...',
    'proj.save': 'Salvar Projeto',
    'proj.delete': 'Excluir',
    'proj.cancel': 'Cancelar',
    'proj.back': 'Voltar',
    'proj.none': 'Nenhum projeto encontrado.',
    'proj.lbl_name': 'Nome do Projeto',
    'proj.lbl_client': 'Cliente',
    'proj.lbl_status': 'Status',
    'proj.lbl_notes': 'Notas Técnicas',
    'proj.lbl_start': 'Data Início',
    'proj.lbl_end': 'Previsão Término',
    'proj.st_pending': 'Pendente',
    'proj.st_progress': 'Em Andamento',
    'proj.st_completed': 'Concluído',
    'proj.st_delayed': 'Atrasado',
    'proj.auto_status': 'Auto (Calendário)',
    'proj.confirm_delete': 'Tem certeza que deseja excluir este projeto?',
  },
  en: {
    'theme.light': 'Light',
    'theme.dark': 'Dark',
    'theme.auto': 'Auto',
    'nav.home': 'Home',
    'nav.tools': 'Tools',
    'nav.projects': 'Projects',
    'nav.ai': 'AI Expert',
    'dash.welcome': 'Welcome back,',
    'dash.engineer': 'Engineer',
    'dash.calc_voltage': 'Calc Voltage',
    'dash.ask_ai': 'Ask AI',
    'dash.daily_summary': 'Daily Summary',
    'dash.today': 'Today',
    'dash.calcs_performed': 'Calculations Performed',
    'dash.pending_projects': 'Pending Projects',
    'dash.add_note': 'Add New Field Note',
    'dash.tip_title': 'TIP OF THE DAY',
    'dash.tip_text': '"Always verify voltage absence with a calibrated tester before touching any conductor. Test-Before-Touch."',
    'dash.backup_title': 'Data Safety',
    'dash.backup_export': 'Backup (Export)',
    'dash.backup_import': 'Restore Data (Import)',
    'dash.backup_success': 'Data restored successfully!',
    'dash.backup_error': 'Failed to read file. Check format.',
    'dash.rate_title': 'Enjoying the App?',
    'dash.rate_desc': 'Your review helps us build more free tools.',
    'dash.rate_btn': 'Rate Us ⭐',
    'tools.title': 'Engineering Tools',
    'tools.voltage_drop': 'Voltage Drop',
    'tools.voltage_drop_desc': 'Calculate VD% based on distance and load.',
    'tools.ohms_law': 'Ohm\'s Law',
    'tools.ohms_law_desc': 'Basic V = I x R relationships.',
    'tools.conduit': 'Conduit Fill',
    'tools.conduit_desc': 'NEC/NBR conduit sizing.',
    'tools.power_factor': 'Power Factor',
    'tools.power_factor_desc': 'Correction capacitor sizing.',
    'tools.breaker': 'Breaker Sizing',
    'tools.breaker_desc': 'Protection device selection.',
    'tools.safety': 'Safety Checklist',
    'tools.safety_desc': 'Pre-task safety verification (LOTO/PPE).',
    'tools.status_dev': 'Coming Soon',
    'tools.status_avail': 'Available',
    'vd.title': 'Voltage Drop Calculator',
    'vd.voltage': 'System Voltage (V)',
    'vd.current': 'Current Load (Amps)',
    'vd.distance': 'One-way Distance (meters)',
    'vd.cable': 'Cable Size (mm²)',
    'vd.material': 'Material',
    'vd.copper': 'Copper (Cu)',
    'vd.aluminum': 'Aluminum (Al)',
    'vd.result_drop': 'Voltage Drop',
    'vd.ok': 'OK',
    'vd.high': 'High Drop',
    'vd.warning': 'Warning: Drop exceeds 4%. Consider increasing cable size to',
    'ohm.title': 'Ohm\'s Law & Power',
    'ohm.subtitle': 'Fill any 2 values to calculate the others.',
    'ohm.v': 'Voltage (V)',
    'ohm.i': 'Current (A)',
    'ohm.r': 'Resistance (Ω)',
    'ohm.p': 'Power (W)',
    'ohm.clear': 'Clear',
    'cf.title': 'Conduit Fill',
    'cf.conduit_size': 'Conduit Size (inch)',
    'cf.wire_size': 'Wire Size (mm²)',
    'cf.num_wires': 'Number of Conductors',
    'cf.max_fill': 'Max Allowed (40%)',
    'cf.actual_fill': 'Actual Fill',
    'cf.status_ok': 'Passed',
    'cf.status_over': 'Overloaded',
    'cf.add_wire': '+ Wire',
    'cf.remove_wire': '- Wire',
    'pf.title': 'Power Factor Correction',
    'pf.active_power': 'Active Power (kW)',
    'pf.current_pf': 'Current Power Factor',
    'pf.target_pf': 'Target Power Factor',
    'pf.required_kvar': 'Required Capacitor Bank',
    'pf.calc_btn': 'Calculate kVAR',
    'cb.title': 'Circuit Breaker Sizing',
    'cb.mode': 'Calculation Mode',
    'cb.mode_p': 'By Power (W)',
    'cb.mode_i': 'By Current (A)',
    'cb.power': 'Load Power (Watts)',
    'cb.voltage': 'Voltage (V)',
    'cb.phases': 'System Phases',
    'cb.pf': 'Power Factor (cos φ)',
    'cb.calc_current': 'Design Current (Ib)',
    'cb.rec_breaker': 'Recommended Breaker (In)',
    'cb.min_cable': 'Suggested Min Cable',
    'cb.note': 'Note: Breaker (In) must be > Design Current (Ib) and < Cable Capacity (Iz).',
    'safe.title': 'Safety Checklist',
    'safe.cat_ppe': 'PPE (Personal Protective Equipment)',
    'safe.cat_proc': 'Procedures & Isolation',
    'safe.cat_tools': 'Tools & Environment',
    'safe.item_head': 'Hard Hat / Helmet',
    'safe.item_eyes': 'Safety Glasses / Visor',
    'safe.item_hands': 'Insulated Gloves (Rated for voltage)',
    'safe.item_boots': 'Dielectric Boots',
    'safe.item_loto': 'Lockout / Tagout (LOTO) Applied',
    'safe.item_test': 'Voltage Absence Verified (Test-Before-Touch)',
    'safe.item_tools': 'Insulated Tools (1000V) in good condition',
    'safe.item_dry': 'Area dry & barricaded if necessary',
    'safe.btn_verify': 'Verify Compliance',
    'safe.alert_title': 'Items Missing!',
    'safe.alert_desc': 'You cannot proceed. Your safety is at risk. Please check the following items:',
    'safe.success_title': 'Safe to Work',
    'safe.success_desc': 'All safety protocols have been verified. Work carefully.',
    'safe.reset': 'New Checklist',
    'ai.title': 'AI Technical Consultant',
    'ai.mode.general': 'General',
    'ai.mode.norm': 'Norms (NEC/NBR)',
    'ai.mode.safety': 'Safety Checks',
    'ai.welcome': 'Hello. I am VoltMaster AI. I can help with NBR/NEC norms, complex calculations, or safety checklists.',
    'ai.analyzing': 'Analyzing parameters...',
    'ai.placeholder.general': 'Describe your electrical problem...',
    'ai.placeholder.norm': 'Ask about cable types, conduit fill...',
    'ai.placeholder.safety': 'Ask for LOTO procedure, PPE...',
    'ai.error': 'Connection trouble. Check API key or network.',
    'ai.disclaimer': 'Disclaimer: AI can make mistakes. Always verify with official technical standards and consult a professional.',
    'proj.title': 'Projects',
    'proj.details': 'Project Details',
    'proj.new_btn': 'New Project',
    'proj.edit_title': 'Edit Project',
    'proj.new_title': 'New Project',
    'proj.search': 'Search by name or client...',
    'proj.save': 'Save Project',
    'proj.delete': 'Delete',
    'proj.cancel': 'Cancel',
    'proj.back': 'Back',
    'proj.none': 'No projects found.',
    'proj.lbl_name': 'Project Name',
    'proj.lbl_client': 'Client',
    'proj.lbl_status': 'Status',
    'proj.lbl_notes': 'Technical Notes',
    'proj.lbl_start': 'Start Date',
    'proj.lbl_end': 'Target Date',
    'proj.st_pending': 'Pending',
    'proj.st_progress': 'In Progress',
    'proj.st_completed': 'Completed',
    'proj.st_delayed': 'Delayed',
    'proj.auto_status': 'Auto (Calendar)',
    'proj.confirm_delete': 'Are you sure you want to delete this project?',
  },
  es: {
    'theme.light': 'Claro',
    'theme.dark': 'Oscuro',
    'theme.auto': 'Auto',
    'nav.home': 'Inicio',
    'nav.tools': 'Herram.',
    'nav.projects': 'Proyectos',
    'nav.ai': 'Experto IA',
    'dash.welcome': 'Bienvenido,',
    'dash.engineer': 'Ingeniero',
    'dash.calc_voltage': 'Calc. Tensión',
    'dash.ask_ai': 'Consultar IA',
    'dash.daily_summary': 'Resumen Diario',
    'dash.today': 'Hoy',
    'dash.calcs_performed': 'Cálculos Realizados',
    'dash.pending_projects': 'Proyectos Pendientes',
    'dash.add_note': 'Agregar Nota de Campo',
    'dash.tip_title': 'CONSEJO DEL DÍA',
    'dash.tip_text': '"Verifique siempre la ausencia de tensión con un probador calibrado antes de tocar. Test-Before-Touch."',
    'dash.backup_title': 'Seguridad de Datos',
    'dash.backup_export': 'Copia de Seguridad (Exportar)',
    'dash.backup_import': 'Restaurar Datos (Importar)',
    'dash.backup_success': '¡Datos restaurados con éxito!',
    'dash.backup_error': 'Error al leer archivo. Verifique formato.',
    'dash.rate_title': '¿Le gusta la App?',
    'dash.rate_desc': 'Su reseña nos ayuda a crear más herramientas gratuitas.',
    'dash.rate_btn': 'Calificar ⭐',
    'tools.title': 'Herramientas de Ingeniería',
    'tools.voltage_drop': 'Caída de Tensión',
    'tools.voltage_drop_desc': 'Calcular % de caída según distancia y carga.',
    'tools.ohms_law': 'Ley de Ohm',
    'tools.ohms_law_desc': 'Relaciones básicas V = I x R.',
    'tools.conduit': 'Ocupación de Ductos',
    'tools.conduit_desc': 'Dimensionamiento NEC/NBR.',
    'tools.power_factor': 'Factor de Potencia',
    'tools.power_factor_desc': 'Corrección de banco de capacitores.',
    'tools.breaker': 'Dim. Disyuntores',
    'tools.breaker_desc': 'Selección de protección según carga.',
    'tools.safety': 'Checklist Seguridad',
    'tools.safety_desc': 'Verificación de seguridad previa (LOTO/EPP).',
    'tools.status_dev': 'Próximamente',
    'tools.status_avail': 'Disponible',
    'vd.title': 'Calculadora Caída de Tensión',
    'vd.voltage': 'Tensión del Sistema (V)',
    'vd.current': 'Corriente (Amperios)',
    'vd.distance': 'Distancia (metros)',
    'vd.cable': 'Sección del Cable (mm²)',
    'vd.material': 'Material',
    'vd.copper': 'Cobre (Cu)',
    'vd.aluminum': 'Aluminio (Al)',
    'vd.result_drop': 'Caída de Tensión',
    'vd.ok': 'OK',
    'vd.high': 'Caída Alta',
    'vd.warning': 'Aviso: Caída excede 4%. Considere aumentar el cable a',
    'ohm.title': 'Ley de Ohm y Potencia',
    'ohm.subtitle': 'Complete 2 valores para calcular el resto.',
    'ohm.v': 'Tensión (V)',
    'ohm.i': 'Corriente (A)',
    'ohm.r': 'Resistencia (Ω)',
    'ohm.p': 'Potencia (W)',
    'ohm.clear': 'Limpiar',
    'cf.title': 'Ocupación de Ductos',
    'cf.conduit_size': 'Tamaño del Ducto (pulg)',
    'cf.wire_size': 'Sección del Cable (mm²)',
    'cf.num_wires': 'Número de Conductores',
    'cf.max_fill': 'Máx Permitido (40%)',
    'cf.actual_fill': 'Ocupación Real',
    'cf.status_ok': 'Aprobado',
    'cf.status_over': 'Sobrecargado',
    'cf.add_wire': '+ Cable',
    'cf.remove_wire': '- Cable',
    'pf.title': 'Corrección de Factor de Potencia',
    'pf.active_power': 'Potencia Activa (kW)',
    'pf.current_pf': 'F.P. Actual',
    'pf.target_pf': 'F.P. Objetivo',
    'pf.required_kvar': 'Banco de Capacitores',
    'pf.calc_btn': 'Calcular kVAR',
    'cb.title': 'Dimensionamiento de Disyuntores',
    'cb.mode': 'Modo de Cálculo',
    'cb.mode_p': 'Por Potencia (W)',
    'cb.mode_i': 'Por Corriente (A)',
    'cb.power': 'Potencia de Carga (Watts)',
    'cb.voltage': 'Tensión (V)',
    'cb.phases': 'Fases del Sistema',
    'cb.pf': 'Factor de Potencia (cos φ)',
    'cb.calc_current': 'Corriente de Diseño (Ib)',
    'cb.rec_breaker': 'Disyuntor Recomendado (In)',
    'cb.min_cable': 'Cable Mínimo Sugerido',
    'cb.note': 'Nota: El disyuntor (In) debe ser mayor que la corriente de diseño (Ib) y menor que la capacidad del cable (Iz).',
    'safe.title': 'Checklist de Seguridad',
    'safe.cat_ppe': 'EPP (Equipo de Protección Personal)',
    'safe.cat_proc': 'Procedimientos y Aislamiento',
    'safe.cat_tools': 'Herramientas y Entorno',
    'safe.item_head': 'Casco de seguridad',
    'safe.item_eyes': 'Lentes de seguridad / Visera',
    'safe.item_hands': 'Guantes aislantes (Clase correcta)',
    'safe.item_boots': 'Botas dieléctricas',
    'safe.item_loto': 'Bloqueio y Etiquetado (LOTO) aplicado',
    'safe.item_test': 'Ausencia de Tensión verificada',
    'safe.item_tools': 'Herramientas aisladas (1000V) en buen estado',
    'safe.item_dry': 'Área seca y señalizada',
    'safe.btn_verify': 'Validar Seguridad',
    'safe.alert_title': '¡Elementos Faltantes!',
    'safe.alert_desc': 'No puede continuar. Su seguridad está en riesgo. Por favor verifique los siguientes elementos:',
    'safe.success_title': 'Seguro para Trabajar',
    'safe.success_desc': 'Todos los protocolos de seguridad han sido verificados. Trabaje con cuidado.',
    'safe.reset': 'Nuevo Checklist',
    'ai.title': 'Consultor Técnico IA',
    'ai.mode.general': 'General',
    'ai.mode.norm': 'Normas (NEC/NBR)',
    'ai.mode.safety': 'Seguridad',
    'ai.welcome': 'Hola. Soy VoltMaster AI. Puedo ayudar con normas NBR/NEC, cálculos o listas de seguridad.',
    'ai.analyzing': 'Analizando parámetros...',
    'ai.placeholder.general': 'Describa su problema eléctrico...',
    'ai.placeholder.norm': 'Pregunte sobre tipos de cables, ductos...',
    'ai.placeholder.safety': 'Pregunte por procedimientos LOTO, EPP...',
    'ai.error': 'Error de conexión. Verifique su red.',
    'ai.disclaimer': 'Aviso: La IA puede cometer errores. Verifique siempre con normas oficiales y consulte a un profesional.',
    'proj.title': 'Proyectos',
    'proj.details': 'Detalles del Proyecto',
    'proj.new_btn': 'Nuevo Proyecto',
    'proj.edit_title': 'Editar Proyecto',
    'proj.new_title': 'Nuevo Proyecto',
    'proj.search': 'Buscar por nombre o cliente...',
    'proj.save': 'Guardar Proyecto',
    'proj.delete': 'Eliminar',
    'proj.cancel': 'Cancelar',
    'proj.back': 'Volver',
    'proj.none': 'No se encontraron proyectos.',
    'proj.lbl_name': 'Nombre del Proyecto',
    'proj.lbl_client': 'Cliente',
    'proj.lbl_status': 'Estado',
    'proj.lbl_notes': 'Notas Técnicas',
    'proj.lbl_start': 'Fecha Inicio',
    'proj.lbl_end': 'Fecha Fin',
    'proj.st_pending': 'Pendiente',
    'proj.st_progress': 'En Progreso',
    'proj.st_completed': 'Completado',
    'proj.st_delayed': 'Atrasado',
    'proj.auto_status': 'Auto (Calendario)',
    'proj.confirm_delete': '¿Está seguro de que desea eliminar este proyecto?',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('pt');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
